---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deploy
  labels: 
    name: postgres-deploy
    app: demo-voting-app
spec:
  selector:
    matchLabels:
      name: postgres-app
      app: demo-voting-app
  template:
    metadata:
      labels:
        name: postgres-app
        app: demo-voting-app
    spec:
      containers:
      - name: myapp
        image: postgres
        ports:
        - containerPort: 5432
        env:
          - name: POSTGRES_USER
            value: "postgres"
          - name: POSTGRES_PASSWORD
            value: "postgres"
          - name: POSTGRES_HOST_AUTH_METHOD
            value: trust
